packages:
  - packages/*
  - apps/*

catalogs:
  formatting:
    oxfmt: ^0.43.0
  testing:
    vitest: ^4.1.2
  types:
    "@types/node": ^24.12.0
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
  typescript:
    typescript: ^6.0.2
  vite:
    vite: ^8.0.14
    "@vitejs/plugin-react": ^6.0.2
  react:
    react: ^19.2.4
    "react-dom": ^19.2.4
  babel:
    "@babel/core": ^7.29.0
    "@rolldown/plugin-babel": ^0.2.1
    "babel-plugin-react-compiler": ^1.0.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
